"""Add progression fields to User

Revision ID: 5d7a4d557c32
Revises: c3a80546ddea
Create Date: 2026-09-05 20:22:46.643951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d7a4d557c32'
down_revision: Union[str, Sequence[str], None] = 'c3a80546ddea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'source')
    op.drop_constraint(op.f('tasks_report_id_fkey'), 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'required_specialization')
    op.drop_column('tasks', 'report_id')
    op.add_column('users', sa.Column('profession', sa.String(), nullable=True))
    op.add_column('users', sa.Column('has_completed_course', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('completed_tasks_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('trial_task_used', sa.Boolean(), server_default='false', nullable=False))
    op.drop_column('users', 'trial_task_done')
    op.drop_column('users', 'specializations')
    op.drop_column('users', 'completed_courses')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('completed_courses', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('specializations', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('trial_task_done', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'trial_task_used')
    op.drop_column('users', 'completed_tasks_count')
    op.drop_column('users', 'has_completed_course')
    op.drop_column('users', 'profession')
    op.add_column('tasks', sa.Column('report_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('required_specialization', postgresql.ENUM('ml_engineer', 'data_analyst', 'ecologist', 'field_volunteer', 'photographer', name='specializationenum'), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('tasks_report_id_fkey'), 'tasks', 'reports', ['report_id'], ['id'])
    op.add_column('reports', sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('reports', 'citizen_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
